#!/usr/bin/env python3
"""Sync Granola meeting notes to markdown files.

Pulls meetings from the official Granola public API (https://public-api.granola.ai)
and exports each as a clean markdown file with YAML frontmatter. Supports
incremental updates via .sync-state.json.

Auth: a `grn_` API key (Granola → Settings → Connectors → API keys; requires a
Business/Enterprise plan), read from the GRANOLA_API_KEY env var or the
`.granola_api_key` file next to this script.

The legacy local-cache decryption path (see load_cache / _decrypt_granola_file)
is retained but dead: Granola 7.42x moved its data-encryption key into an
app-entitlement-gated macOS Keychain item, so user-space scripts can no longer
read the on-disk cache/token/db. See main() → sync_via_api().
"""

import argparse
import base64
import gzip
import hashlib
import json
import os
import re
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime


class TransientNetworkError(RuntimeError):
    """Raised when the API is unreachable due to a transient network condition.

    Treated as a non-failure by main(): logs and exits 0 without a desktop
    notification. Distinct from auth/format errors, which still notify.
    """


class AuthExpiredError(RuntimeError):
    """Raised when the Granola API token has expired (HTTP 401).

    This is a self-healing condition: the Granola desktop app refreshes the
    token whenever it's open. main() treats it as a non-failure (exit 0) but
    sends a single throttled notification so the user knows to open the app,
    rather than emitting a hard error every run.
    """


def _is_transient_network_error(exc):
    if isinstance(exc, (socket.timeout, ConnectionError, TimeoutError)):
        return True
    if isinstance(exc, urllib.error.URLError):
        reason = getattr(exc, "reason", exc)
        return isinstance(reason, (OSError, socket.timeout, socket.gaierror))
    return False

GRANOLA_CACHE_DIR = os.path.expanduser(
    "~/Library/Application Support/Granola"
)


def _find_latest_cache():
    """Find the highest-versioned cache-vN.json (or .json.enc) in Granola's data dir.

    Granola 7.220+ writes encrypted `cache-vN.json.enc` and leaves the plaintext
    `cache-vN.json` as a frozen stub. Prefer the freshest encrypted file when
    present, otherwise fall back to plaintext.
    """
    if not os.path.isdir(GRANOLA_CACHE_DIR):
        return os.path.join(GRANOLA_CACHE_DIR, "cache-v6.json")  # fallback
    candidates = []  # (version, mtime, filename)
    for f in os.listdir(GRANOLA_CACHE_DIR):
        m = re.match(r"^cache-v(\d+)\.json(\.enc)?$", f)
        if m:
            full = os.path.join(GRANOLA_CACHE_DIR, f)
            candidates.append((int(m.group(1)), os.path.getmtime(full), f))
    if not candidates:
        return os.path.join(GRANOLA_CACHE_DIR, "cache-v6.json")  # fallback
    candidates.sort(key=lambda c: (c[0], c[1]), reverse=True)
    return os.path.join(GRANOLA_CACHE_DIR, candidates[0][2])


_cached_dek = None


def _get_dek():
    """Return Granola's 32-byte data encryption key, or None if unavailable.

    The DEK is generated by the app, base64-encoded, then encrypted with
    Electron's `safeStorage.encryptString` (AES-128-CBC, IV=' '*16, key
    derived via PBKDF2 from the keychain entry `Granola Safe Storage`).
    """
    global _cached_dek
    if _cached_dek is not None:
        return _cached_dek
    dek_path = os.path.join(GRANOLA_CACHE_DIR, "storage.dek")
    if not os.path.exists(dek_path):
        return None
    try:
        # Pull keychain password (raw base64 string of the 16-byte AES seed).
        keychain_pw = subprocess.check_output(
            ["security", "find-generic-password",
             "-s", "Granola Safe Storage",
             "-a", "Granola Key", "-w"],
            stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"  Warning: could not read Granola keychain entry: {e}", file=sys.stderr)
        return None
    try:
        from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
        from cryptography.hazmat.primitives.padding import PKCS7
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: F401
    except ImportError:
        print("  Warning: `cryptography` package is required for Granola 7.220+", file=sys.stderr)
        return None

    # Decrypt storage.dek using standard Electron safeStorage scheme on macOS.
    blob = open(dek_path, "rb").read()
    if blob[:3] != b"v10":
        print(f"  Warning: storage.dek has unexpected prefix {blob[:3]!r}", file=sys.stderr)
        return None
    key = hashlib.pbkdf2_hmac("sha1", keychain_pw.encode(), b"saltysalt", 1003, dklen=16)
    cipher = Cipher(algorithms.AES(key), modes.CBC(b" " * 16)).decryptor()
    padded = cipher.update(blob[3:]) + cipher.finalize()
    unpad = PKCS7(128).unpadder()
    try:
        b64_dek = unpad.update(padded) + unpad.finalize()
        dek = base64.b64decode(b64_dek)
    except Exception as e:
        print(f"  Warning: failed to decrypt storage.dek: {e}", file=sys.stderr)
        return None
    if len(dek) != 32:
        print(f"  Warning: DEK has unexpected length {len(dek)}", file=sys.stderr)
        return None
    _cached_dek = dek
    return dek


def _decrypt_granola_file(path):
    """Decrypt a Granola `*.enc` file with the DEK. Returns bytes, or None on failure.

    File layout: [12-byte IV][ciphertext][16-byte GCM tag]. AES-256-GCM.
    """
    dek = _get_dek()
    if dek is None:
        return None
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except ImportError:
        return None
    try:
        blob = open(path, "rb").read()
    except OSError as e:
        print(f"  Warning: could not read {path}: {e}", file=sys.stderr)
        return None
    if len(blob) < 12 + 16:
        return None
    iv, tag, ct = blob[:12], blob[-16:], blob[12:-16]
    try:
        return AESGCM(dek).decrypt(iv, ct + tag, None)
    except Exception as e:
        print(f"  Warning: AES-GCM decrypt failed for {os.path.basename(path)}: {e}", file=sys.stderr)
        return None


DEFAULT_CACHE_PATH = _find_latest_cache()
DEFAULT_OUTPUT_DIR = os.path.expanduser("~/granola-notes")
STATE_FILE = ".sync-state.json"
NOTIFY_STATE_FILE = ".notify-state.json"
NOTIFY_THROTTLE_SECONDS = 4 * 60 * 60  # don't repeat the same notification within 4h
ORPHAN_REMOVAL_MAX_FRACTION = 0.30  # refuse to delete > this fraction of tracked files in one run


# ---------------------------------------------------------------------------
# Tiptap JSON -> Markdown converter
# ---------------------------------------------------------------------------

def tiptap_to_markdown(node, indent=0, ordered_num=None):
    """Recursively convert a Tiptap JSON node to markdown."""
    if node is None:
        return ""

    ntype = node.get("type", "")
    content = node.get("content", [])
    attrs = node.get("attrs", {})

    if ntype == "doc":
        return "\n".join(tiptap_to_markdown(c) for c in content).strip()

    if ntype == "heading":
        level = attrs.get("level", 1)
        text = "".join(tiptap_to_markdown(c) for c in content)
        return f"\n{'#' * level} {text}\n"

    if ntype == "paragraph":
        text = "".join(tiptap_to_markdown(c) for c in content)
        if indent > 0:
            return text
        return f"\n{text}\n"

    if ntype == "bulletList":
        lines = []
        for item in content:
            lines.append(tiptap_to_markdown(item, indent))
        return "\n".join(lines)

    if ntype == "orderedList":
        lines = []
        for i, item in enumerate(content, 1):
            lines.append(tiptap_to_markdown(item, indent, ordered_num=i))
        return "\n".join(lines)

    if ntype == "listItem":
        parts = []
        sub_lists = []
        for c in content:
            if c.get("type") in ("bulletList", "orderedList"):
                sub_lists.append(c)
            else:
                parts.append(c)

        prefix = "  " * indent
        marker = f"{ordered_num}." if ordered_num else "-"
        text = "".join(tiptap_to_markdown(c, indent) for c in parts).strip()
        result = f"{prefix}{marker} {text}"

        for sl in sub_lists:
            result += "\n" + tiptap_to_markdown(sl, indent + 1)

        return result

    if ntype == "text":
        text = node.get("text", "")
        marks = node.get("marks", [])
        for mark in marks:
            mtype = mark.get("type", "")
            if mtype == "bold":
                text = f"**{text}**"
            elif mtype == "italic":
                text = f"*{text}*"
            elif mtype == "link":
                href = mark.get("attrs", {}).get("href", "")
                text = f"[{text}]({href})"
            elif mtype == "code":
                text = f"`{text}`"
        return text

    if ntype == "horizontalRule":
        return "\n---\n"

    if ntype == "hardBreak":
        return "\n"

    if ntype == "codeBlock":
        text = "".join(tiptap_to_markdown(c) for c in content)
        lang = attrs.get("language", "")
        return f"\n```{lang}\n{text}\n```\n"

    if ntype == "blockquote":
        text = "".join(tiptap_to_markdown(c) for c in content)
        return "\n" + "\n".join(f"> {line}" for line in text.strip().split("\n")) + "\n"

    # Unknown node type — render children
    return "".join(tiptap_to_markdown(c, indent) for c in content)


# ---------------------------------------------------------------------------
# Data extraction helpers
# ---------------------------------------------------------------------------

def slugify(text):
    """Convert text to a filename-safe slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")[:80]


def parse_datetime(dt_string):
    """Parse ISO 8601 datetime string, handling timezone offsets."""
    if not dt_string:
        return None
    # Remove colon in timezone offset for Python 3.x < 3.7 compat
    # "2026-01-05T11:45:00-05:00" -> works directly with fromisoformat in 3.7+
    try:
        return datetime.fromisoformat(dt_string)
    except (ValueError, TypeError):
        return None


def get_attendee_name(attendee):
    """Extract the best available name from an attendee dict."""
    if attendee.get("name"):
        return attendee["name"]
    details = attendee.get("details", {})
    person = details.get("person", {})
    name_obj = person.get("name", {})
    if name_obj.get("fullName"):
        return name_obj["fullName"]
    return attendee.get("email", "Unknown")


def extract_meeting_data(doc, panels, folders=None, api_panel=None):
    """Extract structured meeting data from a Granola document."""
    doc_id = doc["id"]
    title = doc.get("title") or "Untitled Meeting"

    # Date and time from calendar event or created_at
    cal_event = doc.get("google_calendar_event")
    duration_minutes = None
    if cal_event and cal_event.get("start", {}).get("dateTime"):
        start_dt = parse_datetime(cal_event["start"]["dateTime"])
        end_dt = parse_datetime(cal_event.get("end", {}).get("dateTime"))
        if start_dt and end_dt:
            duration_minutes = int((end_dt - start_dt).total_seconds() / 60)
    else:
        start_dt = parse_datetime(doc.get("created_at"))

    if not start_dt:
        start_dt = datetime.now()

    date_str = start_dt.strftime("%Y-%m-%d")
    time_str = start_dt.strftime("%H:%M")

    # Attendees
    attendees = []
    people = doc.get("people") or {}
    creator = people.get("creator")
    if creator:
        attendees.append({
            "name": get_attendee_name(creator),
            "email": creator.get("email", ""),
        })
    for att in people.get("attendees", []):
        attendees.append({
            "name": get_attendee_name(att),
            "email": att.get("email", ""),
        })

    # User notes — prefer notes_markdown, fall back to Tiptap conversion
    notes_md = doc.get("notes_markdown", "")
    if not notes_md and doc.get("notes"):
        notes_md = tiptap_to_markdown(doc["notes"])
    notes_md = (notes_md or "").strip()

    # AI summary from documentPanels
    summary_md = ""
    doc_panels = panels.get(doc_id, {})
    for panel_id, panel in doc_panels.items():
        panel_content = panel.get("content")
        if panel_content and isinstance(panel_content, dict):
            summary_md = tiptap_to_markdown(panel_content).strip()
            break
        # Fallback: use original_content (HTML) if no Tiptap
        html = panel.get("original_content", "")
        if html and not summary_md:
            summary_md = html_to_basic_markdown(html)

    # Fallback: use panel from API response
    if not summary_md and api_panel:
        summary_md = tiptap_to_markdown(api_panel).strip()

    return {
        "id": doc_id,
        "title": title,
        "date": date_str,
        "time": time_str,
        "duration_minutes": duration_minutes,
        "attendees": attendees,
        "folders": folders or [],
        "notes": notes_md,
        "summary": summary_md,
        "updated_at": doc.get("updated_at", ""),
    }


def html_to_basic_markdown(html):
    """Minimal HTML to markdown for fallback (handles h3, ul/li, p)."""
    text = html
    text = re.sub(r"<h[1-6][^>]*>", "\n### ", text)
    text = re.sub(r"</h[1-6]>", "\n", text)
    text = re.sub(r"<li[^>]*>", "- ", text)
    text = re.sub(r"</li>", "\n", text)
    text = re.sub(r"<p[^>]*>", "\n", text)
    text = re.sub(r"</p>", "\n", text)
    text = re.sub(r"<strong>", "**", text)
    text = re.sub(r"</strong>", "**", text)
    text = re.sub(r"<em>", "*", text)
    text = re.sub(r"</em>", "*", text)
    text = re.sub(r"<[^>]+>", "", text)  # Strip remaining tags
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def yaml_escape(value):
    """Escape a string value for YAML output."""
    if not isinstance(value, str):
        return str(value)
    # Quote strings that contain special YAML characters
    if any(c in value for c in ":#{}[]|>&*!%@`'\"\\,\n"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if not value:
        return '""'
    return value


def format_transcript(utterances):
    """Format transcript utterances as readable markdown."""
    lines = []
    current_speaker = None
    for utt in utterances:
        speaker = "You" if utt.get("source") == "microphone" else "Other"
        text = utt.get("text", "").strip()
        if not text:
            continue
        ts = utt.get("start_timestamp", "")
        time_str = ""
        if ts:
            dt = parse_datetime(ts)
            if dt:
                time_str = f"[{dt.strftime('%H:%M:%S')}] "
        if speaker != current_speaker:
            lines.append(f"\n**{speaker}:** {time_str}{text}")
            current_speaker = speaker
        else:
            lines.append(f"{time_str}{text}")
    return "\n".join(lines).strip()


def read_existing_user_notes(filepath):
    """Return the text under a '## Notes' heading in an existing note file.

    The public API does not return the user's hand-typed notes, so when we
    refresh an existing file from the API we recover its ## Notes section from
    disk and re-inject it — otherwise a summary refresh would wipe real content.
    """
    try:
        with open(filepath) as f:
            text = f.read()
    except OSError:
        return ""
    m = re.search(r"^## Notes\s*\n(.*?)(?=^## |\Z)", text, re.MULTILINE | re.DOTALL)
    return m.group(1).strip() if m else ""


def build_markdown(data):
    """Build the final markdown file content with YAML frontmatter."""
    lines = ["---"]
    lines.append(f"title: {yaml_escape(data['title'])}")
    lines.append(f"date: {data['date']}")
    lines.append(f'time: "{data["time"]}"')
    if data["duration_minutes"] is not None:
        lines.append(f"duration_minutes: {data['duration_minutes']}")
    if data["attendees"]:
        lines.append("attendees:")
        for att in data["attendees"]:
            lines.append(f"  - name: {yaml_escape(att['name'])}")
            lines.append(f"    email: {att['email']}")
    if data["folders"]:
        lines.append("folders:")
        for folder in data["folders"]:
            lines.append(f"  - {yaml_escape(folder)}")
    lines.append("type: meeting")
    lines.append(f"granola_id: {data['id']}")
    lines.append(f'updated_at: "{data["updated_at"]}"')
    lines.append("---")
    lines.append("")
    lines.append(f"# {data['title']}")
    lines.append("")

    if data["notes"]:
        lines.append("## Notes")
        lines.append("")
        lines.append(data["notes"])
        lines.append("")

    if data["summary"]:
        lines.append("## Summary")
        lines.append("")
        lines.append(data["summary"])
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Sync logic
# ---------------------------------------------------------------------------

def load_cache(cache_path):
    """Load and parse the Granola cache file (plaintext or encrypted)."""
    if cache_path.endswith(".enc"):
        plain = _decrypt_granola_file(cache_path)
        if plain is None:
            return {}
        raw = json.loads(plain.decode("utf-8"))
    else:
        with open(cache_path, "r") as f:
            raw = json.load(f)

    cache_data = raw["cache"]
    if isinstance(cache_data, str):
        cache_data = json.loads(cache_data)
    return cache_data["state"]


def load_api_token():
    """Load the Granola API access token from supabase.json (or .enc).

    Prefers the encrypted file when present and fresher than the plaintext
    one — Granola 7.220+ writes only to supabase.json.enc.
    """
    plain_path = os.path.join(GRANOLA_CACHE_DIR, "supabase.json")
    enc_path = plain_path + ".enc"
    data = None
    if os.path.exists(enc_path) and (
        not os.path.exists(plain_path)
        or os.path.getmtime(enc_path) > os.path.getmtime(plain_path)
    ):
        plain = _decrypt_granola_file(enc_path)
        if plain is not None:
            try:
                data = json.loads(plain.decode("utf-8"))
            except json.JSONDecodeError:
                data = None
    if data is None:
        try:
            with open(plain_path, "r") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError):
            return None
    try:
        workos = data.get("workos_tokens")
        if isinstance(workos, str):
            workos = json.loads(workos)
        return workos.get("access_token") if workos else None
    except (json.JSONDecodeError, KeyError, AttributeError):
        return None


def _api_get_documents(token, doc_ids=None):
    """Fetch documents from the Granola API.

    If doc_ids is provided, fetches those specific documents.
    Otherwise fetches all documents.

    Returns the list of document dicts from the API.
    """
    payload_dict = {"include_last_viewed_panel": True}
    if doc_ids:
        payload_dict["filter_document_ids"] = doc_ids
    payload = json.dumps(payload_dict).encode("utf-8")

    req = urllib.request.Request(
        "https://api.granola.ai/v1/get-documents",
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept-Encoding": "gzip",
            "X-Client-Version": "7.220.0",
            "X-Granola-Platform": "darwin",
        },
        method="POST",
    )

    # Retry transient network errors — Mac may have just woken from sleep or
    # Wi-Fi may be reconnecting. Backoff: 2s, 8s, 20s.
    last_exc = None
    for attempt, delay in enumerate((2, 8, 20, None)):
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                raw = resp.read()
                if resp.headers.get("Content-Encoding") == "gzip":
                    raw = gzip.decompress(raw)
                body = json.loads(raw)
            break
        except Exception as e:
            last_exc = e
            if not _is_transient_network_error(e) or delay is None:
                raise
            time.sleep(delay)
    else:
        raise last_exc

    # Handle API-level errors (e.g. {"message": "Unsupported client"})
    if isinstance(body, dict) and "message" in body and "docs" not in body:
        raise RuntimeError(f"API returned error: {body['message']}")

    return body.get("docs", body) if isinstance(body, dict) else body


def fetch_api_documents(token):
    """Fetch all documents from the Granola API.

    Returns a tuple (documents_dict, api_panels_dict, transient_failure,
    auth_expired) where:
    - documents_dict maps doc_id -> document dict (matching cache format)
    - api_panels_dict maps doc_id -> Tiptap content dict
    - transient_failure is True iff the fetch failed for a transient network reason
    - auth_expired is True iff the API rejected the token with HTTP 401
    """
    documents = {}
    api_panels = {}
    transient_failure = False
    auth_expired = False

    try:
        docs = _api_get_documents(token)
        for doc in docs:
            doc_id = doc.get("id")
            if not doc_id:
                continue
            documents[doc_id] = doc
            panel = doc.get("last_viewed_panel")
            if panel and panel.get("content"):
                api_panels[doc_id] = panel["content"]
    except Exception as e:
        print(f"  Warning: API fetch failed: {e}", file=sys.stderr)
        if isinstance(e, urllib.error.HTTPError) and e.code == 401:
            auth_expired = True
        elif _is_transient_network_error(e):
            transient_failure = True

    return documents, api_panels, transient_failure, auth_expired


def fetch_api_panels(token, doc_ids):
    """Fetch summary panels from the Granola API.

    Returns a dict mapping doc_id -> Tiptap content dict.
    Returns an empty dict on any error.
    """
    if not doc_ids:
        return {}

    result = {}
    batch_size = 100

    for i in range(0, len(doc_ids), batch_size):
        batch = doc_ids[i : i + batch_size]
        try:
            docs = _api_get_documents(token, doc_ids=batch)
            for doc in docs:
                panel = doc.get("last_viewed_panel")
                if panel and panel.get("content"):
                    result[doc["id"]] = panel["content"]
        except Exception:
            continue

    return result


def load_sync_state(output_dir):
    """Load the sync state tracking file."""
    state_path = os.path.join(output_dir, STATE_FILE)
    if os.path.exists(state_path):
        with open(state_path, "r") as f:
            return json.load(f)
    return {}


def save_sync_state(output_dir, state):
    """Save the sync state tracking file."""
    state_path = os.path.join(output_dir, STATE_FILE)
    with open(state_path, "w") as f:
        json.dump(state, f, indent=2)


def sync(cache_path, output_dir, force=False, dry_run=False, verbose=False, no_api=False):
    """Main sync function."""
    log = lambda msg: print(msg) if verbose else None

    log(f"Loading cache from {cache_path}")
    state = load_cache(cache_path)

    documents = state.get("documents", {})
    panels = state.get("documentPanels", {})
    transcripts = state.get("transcripts", {})

    # Fetch documents and panels from API to supplement the cache
    api_panels = {}
    api_transient_failure = False
    api_auth_expired = False
    if not no_api:
        token = load_api_token()
        if token:
            log("Fetching documents from API...")
            api_documents, api_panels, api_transient_failure, api_auth_expired = (
                fetch_api_documents(token)
            )
            # Merge API documents into cache (API wins for existing, adds missing)
            new_from_api = 0
            for doc_id, doc in api_documents.items():
                if doc_id not in documents:
                    new_from_api += 1
                documents[doc_id] = doc
            log(f"  API returned {len(api_documents)} documents ({new_from_api} new beyond cache)")
            log(f"  Fetched {len(api_panels)} panels from API")

            # Also fetch panels for any cache-only docs missing panels
            if not panels:
                cache_only = [d for d in documents if d not in api_panels and not documents[d].get("deleted_at")]
                if cache_only:
                    extra = fetch_api_panels(token, cache_only)
                    api_panels.update(extra)
                    log(f"  Fetched {len(extra)} additional panels for cache-only docs")
        else:
            log("No API token found, skipping API fetch")

    # Build reverse lookup: document_id -> [folder_name, ...]
    doc_lists_meta = state.get("documentListsMetadata", {})
    doc_lists = state.get("documentLists", {})
    doc_folders = {}
    for list_id, doc_ids in doc_lists.items():
        name = doc_lists_meta.get(list_id, {}).get("title")
        if name:
            for did in doc_ids:
                doc_folders.setdefault(did, []).append(name)
    for did in doc_folders:
        doc_folders[did].sort()

    log(f"Found {len(documents)} documents, {len(transcripts)} transcripts")

    os.makedirs(output_dir, exist_ok=True)
    sync_state = load_sync_state(output_dir) if not force else {}

    # Safety guard: if we loaded zero documents but previously synced many, something
    # went wrong (stale cache, API auth failure, format change). Abort rather than
    # deleting every existing file as "orphans". Falls back to counting .md files on
    # disk so the guard still fires if the sync-state file was wiped.
    _prior_doc_count = sum(1 for v in sync_state.values() if v.get("filename"))
    if _prior_doc_count == 0:
        try:
            _prior_doc_count = sum(
                1 for f in os.listdir(output_dir)
                if f.endswith(".md") and not f.endswith("_transcript.md")
            )
        except OSError:
            pass
    if len(documents) == 0 and _prior_doc_count > 5:
        if api_auth_expired:
            raise AuthExpiredError(
                "Granola API token expired — open the Granola app to refresh it. "
                f"Skipping this run ({_prior_doc_count} notes preserved on disk)."
            )
        if api_transient_failure:
            raise TransientNetworkError(
                f"API unreachable; cache produced 0 docs ({_prior_doc_count} on disk). "
                "Skipping this run."
            )
        raise RuntimeError(
            f"Loaded 0 documents but sync state tracks {_prior_doc_count} files. "
            "Cache may be stale or API auth expired. Run with --no-api to use cache "
            "only, or --force to override this check."
        )

    # First pass: determine all filenames to detect collisions
    all_data = {}
    filenames_used = set()
    for doc_id, doc in documents.items():
        if doc.get("deleted_at") or doc.get("was_trashed"):
            log(f"  Skipping deleted: {doc.get('title', doc_id)}")
            continue
        data = extract_meeting_data(
            doc, panels,
            folders=doc_folders.get(doc_id),
            api_panel=api_panels.get(doc_id),
        )
        all_data[doc_id] = data

    # Assign filenames (detect collisions)
    filenames = {}
    filename_counts = {}
    for doc_id, data in all_data.items():
        slug = slugify(data["title"]) or "untitled"
        base = f"{data['date']}_{slug}"
        filename = f"{base}.md"
        if filename in filename_counts:
            filename_counts[filename] += 1
            filename = f"{base}_{doc_id[:8]}.md"
        else:
            filename_counts[filename] = 1
        filenames[doc_id] = filename

    # Handle collisions for the first occurrence too
    for doc_id, data in all_data.items():
        slug = slugify(data["title"]) or "untitled"
        base = f"{data['date']}_{slug}"
        orig_filename = f"{base}.md"
        if filename_counts.get(orig_filename, 0) > 1 and filenames[doc_id] == orig_filename:
            filenames[doc_id] = f"{base}_{doc_id[:8]}.md"

    # Sync each document
    created = 0
    updated = 0
    skipped = 0
    new_sync_state = {}

    for doc_id, data in all_data.items():
        filename = filenames[doc_id]
        prev = sync_state.get(doc_id, {})

        # Check if update needed
        if not force and prev.get("updated_at") == data["updated_at"]:
            new_sync_state[doc_id] = prev
            skipped += 1
            continue

        # Clean up old file if title/date changed (rename detection)
        old_filename = prev.get("filename")
        if old_filename and old_filename != filename:
            old_path = os.path.join(output_dir, old_filename)
            if os.path.exists(old_path):
                if dry_run:
                    log(f"  Would remove old file: {old_filename}")
                else:
                    os.remove(old_path)
                    log(f"  Removed old file: {old_filename}")

        # Write the file
        filepath = os.path.join(output_dir, filename)
        content = build_markdown(data)

        if dry_run:
            action = "create" if not prev else "update"
            log(f"  Would {action}: {filename}")
        else:
            with open(filepath, "w") as f:
                f.write(content)
            if prev:
                updated += 1
                log(f"  Updated: {filename}")
            else:
                created += 1
                log(f"  Created: {filename}")

        new_sync_state[doc_id] = {
            "updated_at": data["updated_at"],
            "filename": filename,
        }

    # Export transcripts (ephemeral in cache — save before Granola evicts them)
    transcripts_saved = 0
    for doc_id, utterances in transcripts.items():
        if not utterances or doc_id not in all_data:
            continue
        prev = new_sync_state.get(doc_id, sync_state.get(doc_id, {}))
        if prev.get("transcript_saved"):
            continue  # Already captured this transcript

        data = all_data[doc_id]
        slug = slugify(data["title"]) or "untitled"
        transcript_filename = f"{data['date']}_{slug}_transcript.md"
        transcript_path = os.path.join(output_dir, transcript_filename)
        transcript_md = format_transcript(utterances)

        if dry_run:
            log(f"  Would save transcript: {transcript_filename} ({len(utterances)} utterances)")
        else:
            with open(transcript_path, "w") as f:
                f.write(f"---\ntitle: \"{data['title']} — Transcript\"\n")
                f.write(f"date: {data['date']}\n")
                f.write(f"granola_id: {doc_id}\n")
                f.write(f"type: transcript\n---\n\n")
                f.write(f"# {data['title']} — Transcript\n\n")
                f.write(transcript_md)
                f.write("\n")
            log(f"  Saved transcript: {transcript_filename} ({len(utterances)} utterances)")

        transcripts_saved += 1
        if doc_id in new_sync_state:
            new_sync_state[doc_id]["transcript_saved"] = True
            new_sync_state[doc_id]["transcript_filename"] = transcript_filename
        else:
            new_sync_state[doc_id] = {
                "updated_at": data["updated_at"],
                "filename": filenames.get(doc_id, ""),
                "transcript_saved": True,
                "transcript_filename": transcript_filename,
            }

    # Clean up files for documents no longer in cache
    # Note: transcript files are preserved even if the document leaves the cache
    orphans = []
    for doc_id, prev in sync_state.items():
        if doc_id not in all_data:
            prev_filename = prev.get("filename", "")
            if prev_filename:
                old_path = os.path.join(output_dir, prev_filename)
                if os.path.exists(old_path):
                    orphans.append((doc_id, prev_filename, old_path))
            # Preserve transcript state so the file isn't orphaned
            if prev.get("transcript_saved"):
                new_sync_state[doc_id] = {
                    "transcript_saved": True,
                    "transcript_filename": prev["transcript_filename"],
                }

    # Safety bound: a sudden mass-orphan is almost always a bug (schema change,
    # partial API response, auth scope shrink). Refuse rather than delete in bulk.
    prior_tracked = sum(1 for v in sync_state.values() if v.get("filename"))
    if (
        not dry_run
        and prior_tracked > 10
        and len(orphans) / prior_tracked > ORPHAN_REMOVAL_MAX_FRACTION
    ):
        raise RuntimeError(
            f"Refusing to remove {len(orphans)} of {prior_tracked} tracked files "
            f"(> {ORPHAN_REMOVAL_MAX_FRACTION:.0%}). This usually indicates a "
            "schema or API change. Inspect the orphan list above, then either "
            "remove the obsolete files manually or delete the corresponding "
            "entries from .sync-state.json before re-running."
        )

    removed = 0
    for _doc_id, prev_filename, old_path in orphans:
        if dry_run:
            log(f"  Would remove orphan: {prev_filename}")
        else:
            os.remove(old_path)
            log(f"  Removed orphan: {prev_filename}")
        removed += 1

    if not dry_run:
        save_sync_state(output_dir, new_sync_state)

    prefix = "[DRY RUN] " if dry_run else ""
    parts = [
        f"{created} created, {updated} updated",
        f"{skipped} unchanged, {removed} removed",
    ]
    if transcripts_saved:
        parts.append(f"{transcripts_saved} transcripts saved")
    print(f"{prefix}Sync complete: {', '.join(parts)}")


# ---------------------------------------------------------------------------
# Official Granola public API (https://public-api.granola.ai)
#
# Replaces the legacy local-cache decryption path. Granola 7.42x moved its data
# encryption key out of the on-disk `storage.dek` file into an app-entitlement-
# gated macOS Keychain item (service `com.granola.app.dek`), and now encrypts
# every local artifact (cache, token, SQLite db) with it — so a user-space
# script can no longer read them. The supported path is the public REST API,
# authenticated with a `grn_` key (Settings → Connectors → API keys; requires a
# Business/Enterprise plan). Notes are keyed by the UUID in `web_url`, which
# matches the `granola_id` the old cache path wrote, so existing files and
# `.sync-state.json` carry over seamlessly.
# ---------------------------------------------------------------------------

API_BASE = "https://public-api.granola.ai/v1"
API_KEY_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), ".granola_api_key"
)


def load_api_key():
    """Load the Granola public-API key (grn_...) from env or the key file."""
    key = os.environ.get("GRANOLA_API_KEY", "").strip()
    if key:
        return key
    try:
        with open(API_KEY_FILE) as f:
            key = f.read().strip()
    except OSError:
        return None
    if not key or key.startswith("grn_PASTE"):
        return None
    return key


def _api_request(path, key, params=None):
    """GET a public-API endpoint and return parsed JSON.

    Raises AuthExpiredError on 401 (bad/expired key), TransientNetworkError on
    429/network failures, RuntimeError on other HTTP errors.
    """
    url = API_BASE + path
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(
        url,
        headers={"Authorization": f"Bearer {key}", "Accept": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        if e.code == 401:
            raise AuthExpiredError(
                "Granola API key rejected (401). Regenerate it in Granola → "
                f"Settings → Connectors → API keys and update {API_KEY_FILE}."
            )
        if e.code == 429:
            raise TransientNetworkError(
                "Granola API rate limit (429); will retry next run."
            )
        body = b""
        try:
            body = e.read()[:200]
        except Exception:
            pass
        raise RuntimeError(f"Granola API HTTP {e.code} for {path}: {body!r}")
    except urllib.error.URLError as e:
        if _is_transient_network_error(e):
            raise TransientNetworkError(f"Granola API unreachable: {e.reason}")
        raise


def fetch_note_list(key, log, page_limit=100):
    """Page through GET /notes, returning every note summary."""
    notes = []
    cursor = None
    while True:
        params = {"limit": page_limit}
        if cursor:
            params["cursor"] = cursor
        data = _api_request("/notes", key, params)
        notes.extend(data.get("notes", []))
        if data.get("hasMore") and data.get("cursor"):
            cursor = data["cursor"]
            log(f"  fetched {len(notes)} note summaries so far...")
        else:
            break
    return notes


def fetch_note_detail(key, note_id):
    """GET a single note with its transcript included."""
    return _api_request(f"/notes/{note_id}", key, {"include": "transcript"})


def _parse_api_dt(s):
    """parse_datetime, tolerant of a trailing 'Z' on older Pythons."""
    if not s:
        return None
    s = s.strip()
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    return parse_datetime(s)


def _api_note_uuid(note):
    web = note.get("web_url") or ""
    if "/" in web:
        return web.rsplit("/", 1)[-1]
    return note.get("id")


def api_note_to_data(note):
    """Map a public-API note detail into the build_markdown() data contract."""
    uuid = _api_note_uuid(note)
    title = note.get("title") or "Untitled Meeting"

    cal = note.get("calendar_event") or {}
    start_dt = _parse_api_dt(cal.get("scheduled_start_time")) or _parse_api_dt(
        note.get("created_at")
    ) or datetime.now()

    duration_minutes = None
    s = _parse_api_dt(cal.get("scheduled_start_time"))
    e = _parse_api_dt(cal.get("scheduled_end_time"))
    if s and e:
        duration_minutes = int((e - s).total_seconds() / 60)

    attendees = []
    for att in note.get("attendees") or []:
        attendees.append({
            "name": att.get("name") or att.get("email", "Unknown"),
            "email": att.get("email", ""),
        })

    folders = []
    for fm in note.get("folder_membership") or []:
        name = fm.get("name") or fm.get("title") or fm.get("folder_name")
        if name:
            folders.append(name)

    summary_md = (
        note.get("summary_markdown") or note.get("summary_text") or ""
    ).strip()

    return {
        "id": uuid,
        "title": title,
        "date": start_dt.strftime("%Y-%m-%d"),
        "time": start_dt.strftime("%H:%M"),
        "duration_minutes": duration_minutes,
        "attendees": attendees,
        "folders": folders,
        # The public API does not expose the user's hand-typed notes, only the
        # AI summary. Left blank; unchanged existing files keep their ## Notes.
        "notes": "",
        "summary": summary_md,
        "updated_at": note.get("updated_at", ""),
    }


def api_transcript_utterances(note):
    """Map public-API transcript entries into format_transcript()'s contract."""
    out = []
    for e in note.get("transcript") or []:
        out.append({
            "source": (e.get("speaker") or {}).get("source", ""),
            "text": e.get("text", ""),
            "start_timestamp": e.get("start_time", ""),
        })
    return out


def sync_via_api(output_dir, force=False, dry_run=False, verbose=False):
    """Sync notes from the official Granola public API into markdown files."""
    log = lambda msg: print(msg) if verbose else None

    key = load_api_key()
    if not key:
        raise RuntimeError(
            "No Granola API key found. Put your grn_ key in "
            f"{API_KEY_FILE} or set the GRANOLA_API_KEY env var."
        )

    os.makedirs(output_dir, exist_ok=True)
    sync_state = load_sync_state(output_dir) if not force else {}

    log("Fetching note list from Granola API...")
    summaries = fetch_note_list(key, log)
    log(f"API returned {len(summaries)} notes")

    prior_on_disk = 0
    if os.path.isdir(output_dir):
        prior_on_disk = sum(
            1 for f in os.listdir(output_dir)
            if f.endswith(".md") and not f.endswith("_transcript.md")
        )
    # API returned nothing but files exist -> transient/auth issue, not a mass
    # deletion. Skip and preserve everything on disk.
    if len(summaries) == 0 and prior_on_disk > 5:
        raise TransientNetworkError(
            f"API returned 0 notes but {prior_on_disk} exist on disk; skipping run."
        )

    # Reverse index: note_id -> (uuid, updated_at) for incremental skips.
    note_index = {}
    for uuid, prev in sync_state.items():
        nid = prev.get("note_id")
        if nid:
            note_index[nid] = (uuid, prev.get("updated_at"))

    created = updated = skipped = transcripts_saved = 0
    # Start from existing state so notes the API doesn't return (e.g. those
    # without an AI summary) are preserved rather than orphaned/deleted.
    new_sync_state = dict(sync_state)
    used_filenames = {
        v.get("filename") for v in sync_state.values() if v.get("filename")
    }

    for summ in summaries:
        note_id = summ.get("id")
        summ_updated = summ.get("updated_at")

        # Fast incremental skip: unchanged since last sync (by note_id).
        if not force and note_id in note_index:
            _uuid, prev_updated = note_index[note_id]
            if prev_updated == summ_updated:
                skipped += 1
                continue

        try:
            note = fetch_note_detail(key, note_id)
        except (TransientNetworkError, AuthExpiredError):
            raise
        except Exception as ex:
            log(f"  skip {note_id}: detail fetch failed: {ex}")
            continue

        data = api_note_to_data(note)
        uuid = data["id"]
        prev = sync_state.get(uuid, {})
        slug = slugify(data["title"]) or "untitled"

        # Preserve an existing .md when content is unchanged. This is the
        # first-run migration case (prior state has no note_id, so the fast
        # skip above misses): don't rewrite the file — it may contain the
        # user's hand-typed ## Notes the API can't return — just backfill
        # note_id and any missing transcript.
        content_unchanged = (
            not force
            and prev.get("filename")
            and prev.get("updated_at") == data["updated_at"]
        )

        entry = dict(prev)
        entry["note_id"] = note_id
        entry["updated_at"] = data["updated_at"]

        if content_unchanged:
            skipped += 1
            filename = prev["filename"]
        else:
            filename = prev.get("filename")
            if not filename:
                filename = f"{data['date']}_{slug}.md"
                if filename in used_filenames:
                    filename = f"{data['date']}_{slug}_{uuid[:8]}.md"
            # Recover the user's hand-typed ## Notes from the existing file
            # (the API can't return them) so a summary refresh preserves them.
            old_filename = prev.get("filename")
            if old_filename and not data["notes"]:
                recovered = read_existing_user_notes(
                    os.path.join(output_dir, old_filename)
                )
                if recovered:
                    data["notes"] = recovered
            # Rename detection (title/date changed).
            if old_filename and old_filename != filename:
                old_path = os.path.join(output_dir, old_filename)
                if os.path.exists(old_path) and not dry_run:
                    os.remove(old_path)

            filepath = os.path.join(output_dir, filename)
            content = build_markdown(data)
            if dry_run:
                log(f"  Would {'update' if prev else 'create'}: {filename}")
            else:
                with open(filepath, "w") as f:
                    f.write(content)
            if prev:
                updated += 1
                log(f"  Updated: {filename}")
            else:
                created += 1
                log(f"  Created: {filename}")
            entry["filename"] = filename

        used_filenames.add(filename)

        # Save transcript once (backfills notes that never had one before).
        utterances = api_transcript_utterances(note)
        if utterances and not entry.get("transcript_saved"):
            transcript_filename = f"{data['date']}_{slug}_transcript.md"
            transcript_path = os.path.join(output_dir, transcript_filename)
            transcript_md = format_transcript(utterances)
            if dry_run:
                log(
                    f"  Would save transcript: {transcript_filename} "
                    f"({len(utterances)} utterances)"
                )
            else:
                with open(transcript_path, "w") as f:
                    f.write(f'---\ntitle: "{data["title"]} — Transcript"\n')
                    f.write(f"date: {data['date']}\n")
                    f.write(f"granola_id: {uuid}\n")
                    f.write("type: transcript\n---\n\n")
                    f.write(f"# {data['title']} — Transcript\n\n")
                    f.write(transcript_md)
                    f.write("\n")
                log(
                    f"  Saved transcript: {transcript_filename} "
                    f"({len(utterances)} utterances)"
                )
            entry["transcript_saved"] = True
            entry["transcript_filename"] = transcript_filename
            transcripts_saved += 1

        new_sync_state[uuid] = entry

    if not dry_run:
        save_sync_state(output_dir, new_sync_state)

    prefix = "[DRY RUN] " if dry_run else ""
    parts = [f"{created} created, {updated} updated", f"{skipped} unchanged"]
    if transcripts_saved:
        parts.append(f"{transcripts_saved} transcripts saved")
    print(f"{prefix}Sync complete: {', '.join(parts)}")


def main():
    parser = argparse.ArgumentParser(
        description="Sync Granola meeting notes to markdown files"
    )
    parser.add_argument(
        "--cache-path",
        default=DEFAULT_CACHE_PATH,
        help=f"Path to Granola cache file (default: {DEFAULT_CACHE_PATH})",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory for markdown files (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force re-export of all documents",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview changes without writing files",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print detailed progress",
    )
    parser.add_argument(
        "--no-api",
        action="store_true",
        help="(Deprecated) legacy local-cache mode; the cache is now encrypted "
             "and unreadable, so this is ignored.",
    )
    args = parser.parse_args()

    try:
        sync_via_api(
            output_dir=args.output_dir,
            force=args.force,
            dry_run=args.dry_run,
            verbose=args.verbose,
        )
    except TransientNetworkError as e:
        print(f"Skipped: {e}", file=sys.stderr)
        sys.exit(0)
    except AuthExpiredError as e:
        # Self-healing once the Granola app refreshes the token. Send one
        # throttled notification so the user knows to open the app, but exit 0
        # so this expected condition isn't treated as a hard failure.
        print(f"Skipped: {e}", file=sys.stderr)
        _notify_error(str(e), args.output_dir)
        sys.exit(0)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        _notify_error(str(e), args.output_dir)
        sys.exit(1)


def _notify_error(message, output_dir=None):
    """Send a macOS notification when the sync fails.

    Throttles per-message: the same message within NOTIFY_THROTTLE_SECONDS is
    suppressed. State is `{message: last_notified_at}` keyed by message text;
    entries older than 24h are pruned so the file can't grow without bound.
    """
    state_path = (
        os.path.join(output_dir, NOTIFY_STATE_FILE) if output_dir else None
    )
    now = time.time()
    history = {}
    if state_path and os.path.exists(state_path):
        try:
            with open(state_path) as f:
                history = json.load(f)
            if not isinstance(history, dict):
                history = {}
        except (OSError, json.JSONDecodeError):
            history = {}

    if now - history.get(message, 0) < NOTIFY_THROTTLE_SECONDS:
        return

    # AppleScript double-quotes need escaping
    safe = message.replace("\\", "\\\\").replace('"', '\\"')
    try:
        subprocess.run(
            [
                "osascript", "-e",
                f'display notification "{safe}" with title "Granola Sync Failed"',
            ],
            capture_output=True,
            timeout=5,
        )
    except Exception:
        return  # notification is best-effort

    history[message] = now
    history = {m: t for m, t in history.items() if now - t < 24 * 60 * 60}
    if state_path:
        try:
            with open(state_path, "w") as f:
                json.dump(history, f)
        except OSError:
            pass


if __name__ == "__main__":
    main()
